/*
 * DFAMainWIn.java
 *
 * Created on 17.09.2009, 20:01:41
 */

package gui;

import controller.IncompleteAutomatonException;
import controller.Simulator;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import models.Dfa;
import models.DfaEditor;
import models.EditorToolStates;
import models.State;
import models.Transition;

/**
 *
 * @author Fabian
 */
public class DFAMainWin extends javax.swing.JFrame {

    Simulator dfaSim = null;
    boolean simBarVisible = false;
    boolean fileChanged = false;
    private int splitSizeInfoBar = 220;
    private int splitSizeSimulationBar = 260;
    private String currentFilename = null;
    HelpFileLoader helpFiles = new HelpFileLoader();



    /** Creates new form DFAMainWIn */
    public DFAMainWin() {
        
        initComponents();
        this.setSize(new Dimension(700, 500));
        centreWindow(this);
      //  this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
    }

    public Simulator getDfaSim() {
        return dfaSim;
    }

    public void setDfaSim(Simulator dfaSim) {
        this.dfaSim = dfaSim;
    }

  private void panelDrawAreaMouseClicked(java.awt.event.MouseEvent evt) {                                           
        if (evt.getClickCount() == 2)
        handleDoubleClick(evt);
    }

/**
 * connect GUI to DFA controller
 */
    public void connectGUItoDFA()
    {
        this.dfaSim.getDfaEditor().setdFAMainWin(this);
        this.dfaSim.getDfaEditor().getdFAPainter().setPaintPanel(this.panelDrawArea);
        this.dfaSim.getDfaEditor().getdFAPainter().setGraphics((Graphics2D)panelDrawArea.getGraphics());
        this.panelDrawArea.setdFAPainter(this.dfaSim.getDfaEditor().getdFAPainter());
        updateButtons();
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator3 = new javax.swing.JSeparator();
        jToolBar1 = new javax.swing.JToolBar();
        togglePointer = new javax.swing.JToggleButton();
        toggleAddState = new javax.swing.JToggleButton();
        toggleAddTransition = new javax.swing.JToggleButton();
        panelContainer = new javax.swing.JPanel();
        splitterInfobar = new javax.swing.JSplitPane();
        panelMainDrawArea = new javax.swing.JPanel();
        splitterSimulationBar = new javax.swing.JSplitPane();
        panelTop = new javax.swing.JPanel();
        panelDrawArea = new gui.PaintPanel();
        panelConsole = new javax.swing.JPanel();
        panelConsoleTop = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonNextStep = new javax.swing.JButton();
        buttonSimulateAll = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textareaInputWord = new javax.swing.JTextArea();
        buttonReset = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textareaOutput = new javax.swing.JTextArea();
        panelHelpSide = new javax.swing.JPanel();
        SplitterDescriptionHelp = new javax.swing.JSplitPane();
        panelDFADesc = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        textDescription = new javax.swing.JTextPane();
        panelHELP = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        editorHelp = new javax.swing.JEditorPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuitemNewDFA = new javax.swing.JMenuItem();
        menuitemOpen = new javax.swing.JMenuItem();
        menuitemSave = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JSeparator();
        menuitemExit = new javax.swing.JMenuItem();
        menuDFA = new javax.swing.JMenu();
        menuitemExportImage = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        menuitemProperties = new javax.swing.JMenuItem();
        menuItemMinimizeDfa = new javax.swing.JMenuItem();
        menuitemAutocomplete = new javax.swing.JMenuItem();
        menuSimulation = new javax.swing.JMenu();
        menuitemStartSim = new javax.swing.JMenuItem();
        menuItemStopSim = new javax.swing.JMenuItem();
        menuInfo = new javax.swing.JMenu();
        menuitemInfo = new javax.swing.JMenuItem();
        menuFile.add(jSeparator3);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("DFA Simulator");
        setBounds(new java.awt.Rectangle(0, 0, 600, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                formAncestorResized(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jToolBar1.setRollover(true);
        jToolBar1.setName("Tools"); // NOI18N

        togglePointer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/img/icon_pointer.png"))); // NOI18N
        togglePointer.setSelected(true);
        togglePointer.setToolTipText("Pointer");
        togglePointer.setFocusable(false);
        togglePointer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        togglePointer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        togglePointer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togglePointerActionPerformed(evt);
            }
        });
        jToolBar1.add(togglePointer);

        toggleAddState.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/img/icon_addstate.png"))); // NOI18N
        toggleAddState.setToolTipText("Add state");
        toggleAddState.setFocusable(false);
        toggleAddState.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toggleAddState.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toggleAddState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleAddStateActionPerformed(evt);
            }
        });
        jToolBar1.add(toggleAddState);
        toggleAddState.getAccessibleContext().setAccessibleDescription("Add State");

        toggleAddTransition.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/img/icon_addtransition.png"))); // NOI18N
        toggleAddTransition.setToolTipText("Add Transition");
        toggleAddTransition.setFocusable(false);
        toggleAddTransition.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toggleAddTransition.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toggleAddTransition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleAddTransitionActionPerformed(evt);
            }
        });
        jToolBar1.add(toggleAddTransition);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.NORTH);

        panelContainer.setLayout(new java.awt.BorderLayout());

        splitterInfobar.setDividerLocation(550);
        splitterInfobar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                splitterInfobarMouseReleased(evt);
            }
        });
        splitterInfobar.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                splitterInfobarComponentMoved(evt);
            }
        });
        splitterInfobar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                splitterInfobarPropertyChange(evt);
            }
        });

        panelMainDrawArea.setLayout(new java.awt.BorderLayout());

        splitterSimulationBar.setDividerLocation(250);
        splitterSimulationBar.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        panelTop.setPreferredSize(new java.awt.Dimension(100, 600));
        panelTop.setLayout(new java.awt.BorderLayout());

        panelDrawArea.setBackground(new java.awt.Color(255, 255, 255));
        panelDrawArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelDrawAreaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelDrawAreaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelDrawAreaMouseReleased(evt);
            }
        });
        panelDrawArea.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                panelDrawAreaComponentShown(evt);
            }
        });
        panelDrawArea.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelDrawAreaMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelDrawAreaMouseMoved(evt);
            }
        });
        panelDrawArea.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                panelDrawAreaAncestorResized(evt);
            }
        });
        panelDrawArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                panelDrawAreaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelDrawAreaLayout = new javax.swing.GroupLayout(panelDrawArea);
        panelDrawArea.setLayout(panelDrawAreaLayout);
        panelDrawAreaLayout.setHorizontalGroup(
            panelDrawAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
        );
        panelDrawAreaLayout.setVerticalGroup(
            panelDrawAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 249, Short.MAX_VALUE)
        );

        panelTop.add(panelDrawArea, java.awt.BorderLayout.CENTER);

        splitterSimulationBar.setTopComponent(panelTop);

        panelConsole.setLayout(new java.awt.BorderLayout());

        panelConsoleTop.setMinimumSize(new java.awt.Dimension(10, 20));
        panelConsoleTop.setPreferredSize(new java.awt.Dimension(573, 90));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel1.setText("Simulation");

        buttonNextStep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/img/icon_play.png"))); // NOI18N
        buttonNextStep.setText("Next");
        buttonNextStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNextStepActionPerformed(evt);
            }
        });

        buttonSimulateAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/img/icon_fastfwd.png"))); // NOI18N
        buttonSimulateAll.setText("All");
        buttonSimulateAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimulateAllActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel2.setText("Input word");

        textareaInputWord.setColumns(20);
        textareaInputWord.setRows(5);
        jScrollPane2.setViewportView(textareaInputWord);

        buttonReset.setText("Reset");
        buttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelConsoleTopLayout = new javax.swing.GroupLayout(panelConsoleTop);
        panelConsoleTop.setLayout(panelConsoleTopLayout);
        panelConsoleTopLayout.setHorizontalGroup(
            panelConsoleTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConsoleTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConsoleTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelConsoleTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelConsoleTopLayout.createSequentialGroup()
                        .addComponent(buttonNextStep)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSimulateAll))
                    .addGroup(panelConsoleTopLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonReset)))
                .addGap(176, 176, 176))
        );
        panelConsoleTopLayout.setVerticalGroup(
            panelConsoleTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsoleTopLayout.createSequentialGroup()
                .addGroup(panelConsoleTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConsoleTopLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(panelConsoleTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(buttonReset)))
                    .addGroup(panelConsoleTopLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelConsoleTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .addGroup(panelConsoleTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(buttonNextStep)
                                .addComponent(buttonSimulateAll)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        panelConsole.add(panelConsoleTop, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        textareaOutput.setColumns(20);
        textareaOutput.setEditable(false);
        textareaOutput.setRows(5);
        jScrollPane1.setViewportView(textareaOutput);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        panelConsole.add(jPanel2, java.awt.BorderLayout.CENTER);

        splitterSimulationBar.setRightComponent(panelConsole);

        panelMainDrawArea.add(splitterSimulationBar, java.awt.BorderLayout.CENTER);

        splitterInfobar.setLeftComponent(panelMainDrawArea);

        panelHelpSide.setLayout(new java.awt.BorderLayout());

        SplitterDescriptionHelp.setDividerLocation(150);
        SplitterDescriptionHelp.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jLabel6.setText("DFA-Description");

        textDescription.setBackground(new java.awt.Color(236, 233, 222));
        textDescription.setBorder(null);
        textDescription.setEditable(false);
        jScrollPane4.setViewportView(textDescription);

        javax.swing.GroupLayout panelDFADescLayout = new javax.swing.GroupLayout(panelDFADesc);
        panelDFADesc.setLayout(panelDFADescLayout);
        panelDFADescLayout.setHorizontalGroup(
            panelDFADescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDFADescLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDFADescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(jLabel6))
                .addContainerGap())
        );
        panelDFADescLayout.setVerticalGroup(
            panelDFADescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDFADescLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addContainerGap())
        );

        SplitterDescriptionHelp.setTopComponent(panelDFADesc);

        jLabel5.setText("Context Help");

        editorHelp.setContentType("text/html");
        editorHelp.setEditable(false);
        jScrollPane3.setViewportView(editorHelp);

        javax.swing.GroupLayout panelHELPLayout = new javax.swing.GroupLayout(panelHELP);
        panelHELP.setLayout(panelHELPLayout);
        panelHELPLayout.setHorizontalGroup(
            panelHELPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHELPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(203, Short.MAX_VALUE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
        );
        panelHELPLayout.setVerticalGroup(
            panelHELPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHELPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE))
        );

        SplitterDescriptionHelp.setRightComponent(panelHELP);

        panelHelpSide.add(SplitterDescriptionHelp, java.awt.BorderLayout.CENTER);

        splitterInfobar.setRightComponent(panelHelpSide);

        panelContainer.add(splitterInfobar, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelContainer, java.awt.BorderLayout.CENTER);

        jMenuBar1.setName("Tools"); // NOI18N

        menuFile.setText("File");

        menuitemNewDFA.setText("New DFA");
        menuitemNewDFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemNewDFAActionPerformed(evt);
            }
        });
        menuFile.add(menuitemNewDFA);

        menuitemOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/img/iconopenfile.png"))); // NOI18N
        menuitemOpen.setText("Open File...");
        menuitemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemOpenActionPerformed(evt);
            }
        });
        menuFile.add(menuitemOpen);

        menuitemSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/img/iconsavefile.png"))); // NOI18N
        menuitemSave.setText("Save File...");
        menuitemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemSaveActionPerformed(evt);
            }
        });
        menuFile.add(menuitemSave);
        menuFile.add(jSeparator3);

        menuitemExit.setText("Exit");
        menuitemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemExitActionPerformed(evt);
            }
        });
        menuFile.add(menuitemExit);

        jMenuBar1.add(menuFile);

        menuDFA.setText("DFA");

        menuitemExportImage.setText("Image Export");
        menuitemExportImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemExportImageActionPerformed(evt);
            }
        });
        menuDFA.add(menuitemExportImage);
        menuDFA.add(jSeparator1);

        menuitemProperties.setText("Description and Alphabet...");
        menuitemProperties.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemPropertiesActionPerformed(evt);
            }
        });
        menuDFA.add(menuitemProperties);

        menuItemMinimizeDfa.setText("Minimize DFA");
        menuItemMinimizeDfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMinimizeDfaActionPerformed(evt);
            }
        });
        menuDFA.add(menuItemMinimizeDfa);

        menuitemAutocomplete.setText("Autocomplete DFA...");
        menuitemAutocomplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemAutocompleteActionPerformed(evt);
            }
        });
        menuDFA.add(menuitemAutocomplete);

        jMenuBar1.add(menuDFA);

        menuSimulation.setText("Simulation");

        menuitemStartSim.setText("Start Simulation");
        menuitemStartSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemStartSimActionPerformed(evt);
            }
        });
        menuSimulation.add(menuitemStartSim);

        menuItemStopSim.setText("Stop Simulation");
        menuItemStopSim.setEnabled(false);
        menuItemStopSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemStopSimActionPerformed(evt);
            }
        });
        menuSimulation.add(menuItemStopSim);

        jMenuBar1.add(menuSimulation);

        menuInfo.setText("Info");
        menuInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInfoActionPerformed(evt);
            }
        });

        menuitemInfo.setText("About DFA Simulator");
        menuitemInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemInfoActionPerformed(evt);
            }
        });
        menuInfo.add(menuitemInfo);

        jMenuBar1.add(menuInfo);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInfoActionPerformed

    }//GEN-LAST:event_menuInfoActionPerformed

    private void menuitemInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemInfoActionPerformed
        //-- create and show new Info window --
        DFAInfoWin infowin = new DFAInfoWin();
        infowin.setVisible(true);
    }//GEN-LAST:event_menuitemInfoActionPerformed

    private void menuitemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemExitActionPerformed
       setVisible(false);
       dispose();
    }//GEN-LAST:event_menuitemExitActionPerformed

    /** 
     * updates the Sidebar with DFA info panel and help function
     */
    public void updateSidebar()
    {
       if (getDfaSim() != null)
       {
        if (getDfaSim().getDfa().getDescription().length() == 0)
        {
           panelDFADesc.setVisible(false);
           SplitterDescriptionHelp.setDividerSize(1);

        } else
        {
           panelDFADesc.setVisible(true);
           textDescription.setText(getDfaSim().getDfa().getDescription());
           if (SplitterDescriptionHelp.getDividerLocation() < 30)
               SplitterDescriptionHelp.setDividerLocation(120);
           SplitterDescriptionHelp.setDividerSize(5);
        }
       }
    }
    


    private void menuitemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemOpenActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileFilter(new FileNameExtensionFilter("DFA Simulator Files", "dfa"));
        int retVal = fc.showOpenDialog(this);
        Dfa loaded_dfa = null;
        if(retVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();

            try {
                ObjectInputStream in = new ObjectInputStream(new BufferedInputStream(new FileInputStream(file)));
                loaded_dfa = (Dfa) in.readObject();
                in.close();
            } catch (IOException ex) {
                String msg = "File not found!";
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error: File not found", JOptionPane.WARNING_MESSAGE);
            } catch (ClassNotFoundException ex) {
                System.out.println(ex.getMessage());
            }
            currentFilename = fc.getSelectedFile().getName();
        }

        stopSimulation();

        fileChanged = false;
        this.dfaSim.getDfaEditor().resetEditor();
        dfaSim.setDfa(loaded_dfa);

        connectGUItoDFA();
        panelDrawArea.repaint();
        setWindowCaption();
    }//GEN-LAST:event_menuitemOpenActionPerformed


    private void setWindowCaption()
    {
        String winName = "DFA Simulator";
        if (currentFilename == null)
        {
            this.setTitle(winName);
        } else
        {
            if (fileChanged)
                this.setTitle(winName+" - "+currentFilename+"*"); else
                this.setTitle(winName+" - "+currentFilename);
        }
    }

    private void toggleAddTransitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleAddTransitionActionPerformed
        getDfaSim().getDfaEditor().setToolState(EditorToolStates.addTransition);
        dfaSim.getDfaEditor().removeAllSelections();
        updateButtons();
        repaint();
    }//GEN-LAST:event_toggleAddTransitionActionPerformed

    private void togglePointerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togglePointerActionPerformed
        getDfaSim().getDfaEditor().setToolState(EditorToolStates.handTool);
        dfaSim.getDfaEditor().removeAllSelections();
        updateButtons();
        repaint();
    }//GEN-LAST:event_togglePointerActionPerformed

    private void toggleAddStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleAddStateActionPerformed
        getDfaSim().getDfaEditor().setToolState(EditorToolStates.addState);
        dfaSim.getDfaEditor().removeAllSelections();
        updateButtons();
        repaint();
    }//GEN-LAST:event_toggleAddStateActionPerformed

    private void menuitemPropertiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemPropertiesActionPerformed
        DFAPropertiesWin dwin = new DFAPropertiesWin();

        dwin.setDfa(getDfaSim().getDfa());
        dwin.setdFAMainWin(this);
        dwin.setAlwaysOnTop(true);
        dwin.setVisible(true);


    }//GEN-LAST:event_menuitemPropertiesActionPerformed

    private void buttonSimulateAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimulateAllActionPerformed
        while(dfaSim.getIsRunning()) {
            doNextStep();
        }
        panelDrawArea.repaint();
    }//GEN-LAST:event_buttonSimulateAllActionPerformed

    private void buttonNextStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNextStepActionPerformed
       doNextStep();
       panelDrawArea.repaint();
    }//GEN-LAST:event_buttonNextStepActionPerformed

    private void doNextStep() {
        String inputWord = textareaInputWord.getText();
        Dfa dfa = dfaSim.getDfa();
        State activeState = dfa.getCurrentState();
        State nextState;
        //handle the empty word
        if (!inputWord.equals("")) {
            if (!dfaSim.getIsRunning()) {
                try {
                    dfaSim.startSimulation(inputWord);
                    textareaInputWord.setEditable(false);
                } catch (IncompleteAutomatonException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage(), "Cannot start simulation", JOptionPane.WARNING_MESSAGE);
                }
            }
            int pos = dfa.getCurrentPosition();
            dfaSim.nextStep();
            nextState = dfa.getCurrentState();
            highlightCurrentPosition(pos);
            outputInfo(activeState, nextState, pos);
        }
        if(!dfaSim.getIsRunning()) {
            //All input has been read
            buttonNextStep.setEnabled(false);
            buttonSimulateAll.setEnabled(false);
            String acceptMsg = "The DFA ";
            if(dfaSim.isAccepting()) {
                acceptMsg += "ACCEPTS the input word!";
            } else {
                acceptMsg += "does NOT accept the input word!";
            }
            textareaOutput.setText(textareaOutput.getText()+acceptMsg);
        }
    }
    private void outputInfo(State fromState, State toState, int pos) {
        String input = textareaInputWord.getText().substring(pos, pos+1);
        String msg = "Reading input '"+input+"' and taking Transition from State ";
        msg += fromState.getState_Properties().getName()+" to State ";
        msg += toState.getState_Properties().getName()+".\n";
        textareaOutput.setText(textareaOutput.getText()+msg);
    }
    private void highlightCurrentPosition(int pos) {
        textareaInputWord.requestFocus();
        textareaInputWord.setSelectionColor(Color.red);
        textareaInputWord.setSelectionStart(pos);
        textareaInputWord.setSelectionEnd(pos+1);
    }
    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
        textareaInputWord.setEditable(true);
        textareaOutput.setText("");
        buttonNextStep.setEnabled(true);
        buttonSimulateAll.setEnabled(true);
        dfaSim.resetDfa();
        panelDrawArea.repaint();
    }//GEN-LAST:event_buttonResetActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       connectGUItoDFA();
       repaint();
    }//GEN-LAST:event_formWindowOpened

    private void panelDrawAreaAncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_panelDrawAreaAncestorResized

    }//GEN-LAST:event_panelDrawAreaAncestorResized

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       
    }//GEN-LAST:event_formWindowActivated

    private void panelDrawAreaComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panelDrawAreaComponentShown

    }//GEN-LAST:event_panelDrawAreaComponentShown

    private void panelDrawAreaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDrawAreaMousePressed
        getDfaSim().getDfaEditor().handleMousePressed(evt);
        fileChanged = true;
        setWindowCaption();

    }//GEN-LAST:event_panelDrawAreaMousePressed

    private void panelDrawAreaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDrawAreaMouseReleased
        panelDrawArea.requestFocus();
        getDfaSim().getDfaEditor().handleMouseReleased(evt);
        
    }//GEN-LAST:event_panelDrawAreaMouseReleased

    private void panelDrawAreaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDrawAreaMouseMoved
        getDfaSim().getDfaEditor().handleMouseMoved(evt);

    }//GEN-LAST:event_panelDrawAreaMouseMoved

    private void panelDrawAreaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDrawAreaMouseDragged
        getDfaSim().getDfaEditor().handleMouseDragged(evt);
    }//GEN-LAST:event_panelDrawAreaMouseDragged

    private void menuitemStartSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemStartSimActionPerformed
        startSimulation();
    }//GEN-LAST:event_menuitemStartSimActionPerformed

    private void startSimulation()
    {
        this.simBarVisible = true;
        panelConsole.setVisible(true);
        splitterSimulationBar.setDividerLocation(0.65);
        menuItemStopSim.setEnabled(true);
        menuitemStartSim.setEnabled(false);
        dfaSim.getDfaEditor().setIsEditable(false);
        dfaSim.getDfaEditor().setToolState(EditorToolStates.noTool);
        dfaSim.setSimulationModeActive(true);
        dfaSim.getDfaEditor().removeAllSelections();
        updateButtons();
    }

    private void menuitemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemSaveActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileFilter(new FileNameExtensionFilter("DFA Simulator Files", "dfa"));
        int retVal = fc.showSaveDialog(this);
        if (retVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            String fpath = file.getPath();

            if (!fpath.toLowerCase().endsWith(".dfa")) {
                String newName = fpath + ".dfa";
                file = new File(newName);
            }
            if (file.exists()) {
                String msg = "The file you have chosen already exists! Do you want to overwrite this file?";
                retVal = JOptionPane.showConfirmDialog(this, msg, "Overwrite?", JOptionPane.YES_NO_CANCEL_OPTION);
            } else {
                retVal = JOptionPane.YES_OPTION;
            }
            switch (retVal) {
                case JOptionPane.YES_OPTION:
                    try {
                        ObjectOutputStream out = null;
                        out = new ObjectOutputStream(new BufferedOutputStream(new FileOutputStream(file)));
                        out.writeObject(this.dfaSim.getDfa());
                        fileChanged = false;
                         currentFilename = fc.getSelectedFile().getName();
                        setWindowCaption();
                        out.close();
                    } catch (FileNotFoundException ex) {
                        //TODO
                        String msg = "File not found!";
                        JOptionPane.showMessageDialog(this, msg, "Error: File not found", JOptionPane.WARNING_MESSAGE);
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.WARNING_MESSAGE);
                    }
                    break;
                case JOptionPane.NO_OPTION:
                    menuitemSaveActionPerformed(evt);
                    break;
                default:
                    //do nothing
            }
        }
    }//GEN-LAST:event_menuitemSaveActionPerformed

    private void menuItemStopSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemStopSimActionPerformed
        stopSimulation();
    }//GEN-LAST:event_menuItemStopSimActionPerformed

    private void stopSimulation()
    {
        this.simBarVisible = false;
        panelConsole.setVisible(false);
        menuItemStopSim.setEnabled(false);
        menuitemStartSim.setEnabled(true);
        dfaSim.getDfaEditor().setIsEditable(true);
        dfaSim.getDfaEditor().setToolState(EditorToolStates.handTool);
        dfaSim.setSimulationModeActive(false);
        updateButtons();
    }

    private void panelDrawAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelDrawAreaKeyPressed
     getDfaSim().getDfaEditor().handleEditorKeyPressed(evt);
        
    }//GEN-LAST:event_panelDrawAreaKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

        
    }//GEN-LAST:event_formKeyPressed

    private void menuitemNewDFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemNewDFAActionPerformed
        createNewDFA();
        stopSimulation();
    }//GEN-LAST:event_menuitemNewDFAActionPerformed

    private void controlSplitPaneSizes()
    {
        splitterInfobar.setDividerLocation(this.getWidth()-splitSizeInfoBar);
        splitterSimulationBar.setDividerLocation(this.getHeight()-splitSizeSimulationBar);


    }


    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (fileChanged)
        {
            if (askUserMessageBoxYesNo("Exit", "Exit program without saving?"))
            {
                System.exit(0);
            }
        } else
            System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void formAncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_formAncestorResized

    }//GEN-LAST:event_formAncestorResized

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
         controlSplitPaneSizes();
    }//GEN-LAST:event_formComponentResized

    private void splitterInfobarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_splitterInfobarMouseReleased
       
    }//GEN-LAST:event_splitterInfobarMouseReleased

    private void splitterInfobarComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_splitterInfobarComponentMoved

    }//GEN-LAST:event_splitterInfobarComponentMoved

    private void splitterInfobarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_splitterInfobarPropertyChange

    }//GEN-LAST:event_splitterInfobarPropertyChange

    private void menuItemMinimizeDfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMinimizeDfaActionPerformed
        Dfa minimized = null;
        try {
            minimized = dfaSim.minimizeDfa(dfaSim.getDfa());
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.WARNING_MESSAGE);
        }
        dfaSim.setDfa(minimized);
        dfaSim.getDfa().autoArrangeDFA();
        panelDrawArea.repaint();
    }//GEN-LAST:event_menuItemMinimizeDfaActionPerformed

    private void menuitemExportImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemExportImageActionPerformed
  JFileChooser fc = new JFileChooser();
        fc.setFileFilter(new FileNameExtensionFilter("PNG Image Files (lossless)", "png"));
        int retVal = fc.showSaveDialog(this);
        if (retVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            String fpath = file.getPath();

            if (!fpath.toLowerCase().endsWith(".png")) {
                String newName = fpath + ".png";
                file = new File(newName);
            }
            

            if (file.exists()) {
                String msg = "The file you have chosen already exists! Do you want to overwrite this file?";
                retVal = JOptionPane.showConfirmDialog(this, msg, "Overwrite?", JOptionPane.YES_NO_CANCEL_OPTION);
            } else {
                retVal = JOptionPane.YES_OPTION;
            }
            switch (retVal) {
                case JOptionPane.YES_OPTION:

                    if (getDfaSim().getDfaEditor().getdFAPainter().exportPNGFile(file))
                        repaint();
                   break;
                case JOptionPane.NO_OPTION:
                    menuitemExportImageActionPerformed(evt);
                    break;
                default:
                    //do nothing
            }
        }
    }//GEN-LAST:event_menuitemExportImageActionPerformed

    private void menuitemAutocompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemAutocompleteActionPerformed
        DFAAutoCompleteWin win = new DFAAutoCompleteWin();
        win.setAlwaysOnTop(true);
        win.setdFAMainWin(this);
        win.setSim(dfaSim);
        win.setVisible(true);
    }//GEN-LAST:event_menuitemAutocompleteActionPerformed


    private void createNewDFA()
    {
        if (askUserMessageBoxYesNo("new DFA", "Do you want to create an empty DFA?"))
        {
            Dfa ndfa = new Dfa();
            currentFilename = null;
            fileChanged = false;
            getDfaSim().getDfaEditor().setDfa(ndfa);
            this.getDfaSim().setDfa(ndfa);
            repaint();
        }
    }



    private void handleDoubleClick(java.awt.event.MouseEvent evt)
    {
        getDfaSim().getDfaEditor().handleDoubleClick(evt);
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DFAMainWin().setVisible(true);
                
            }
        });
    }

public static void centreWindow(JFrame frame) {
    Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
    int x = (int) ((dimension.getWidth() - frame.getWidth()) / 2);
    int y = (int) ((dimension.getHeight() - frame.getHeight()) / 2);
    frame.setLocation(x, y);
}


public void updateButtons()
{
    panelConsole.setVisible(simBarVisible);
    updateToolButtons();
    updateSidebar();
    manageHelp();
}

public void manageHelp()
{
    String currentSite = "";
    if (!getDfaSim().isSimulationModeActive())
    {
        if (getDfaSim().getDfaEditor().getToolState() == EditorToolStates.handTool)
       currentSite = "handtool";
        if (getDfaSim().getDfaEditor().getToolState() == EditorToolStates.addState)
        currentSite = "addstatetool";
        if (getDfaSim().getDfaEditor().getToolState() == EditorToolStates.addTransition)
        currentSite = "addtransitiontool";
      
    } else
        currentSite ="simulation";

    if (currentSite != "")
        showHelpFile(currentSite);

}

public void showHelpFile(String pageName)
{
        try {
            editorHelp.setPage(helpFiles.getUrlByKey(pageName));
        } catch (IOException ex) {
            
        }
}

/**
 * update the UIButtons for the tools
 */
public void updateToolButtons()
{
    DfaEditor e = this.dfaSim.getDfaEditor();
    
    togglePointer.setSelected(e.getToolState() == EditorToolStates.handTool);
    toggleAddState.setSelected(e.getToolState() == EditorToolStates.addState);
    toggleAddTransition.setSelected(e.getToolState() == EditorToolStates.addTransition);
    
    togglePointer.setEnabled(e.isEditable());
    toggleAddState.setEnabled(e.isEditable());
    toggleAddTransition.setEnabled(e.isEditable());
}

public void showStateEditWin(State s, boolean newState)
{
        DFAStatePropertiesWin stprowin = new DFAStatePropertiesWin();
        stprowin.setAlwaysOnTop(true);
        stprowin.setState(s);
        stprowin.setdFAMainWin(this);
        stprowin.setNewElement(newState);
        stprowin.setVisible(true);
        stprowin.requestFocus();
        this.dfaSim.getDfaEditor().setWaitForEditWindow(true);
}

public void showTransEditWin(Transition t, boolean newTrans)
{
        DFATransitionWin trwin = new DFATransitionWin();
        trwin.setAlwaysOnTop(true);
        trwin.setTransition(t);
        trwin.setdFAMainWin(this);
        trwin.setnewElement(newTrans);
        trwin.setVisible(true);
        trwin.requestFocus();
        this.dfaSim.getDfaEditor().setWaitForEditWindow(true);
}

public void handleCloseEditWindow()
{
    this.dfaSim.getDfaEditor().setWaitForEditWindow(false);
}

public boolean askUserMessageBoxYesNo(String title, String message)
{
    int n = JOptionPane.showConfirmDialog(
        this,
        message,
        title,
        JOptionPane.YES_NO_OPTION);
    return n == 0;

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane SplitterDescriptionHelp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonNextStep;
    private javax.swing.JButton buttonReset;
    private javax.swing.JButton buttonSimulateAll;
    private javax.swing.JEditorPane editorHelp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu menuDFA;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuInfo;
    private javax.swing.JMenuItem menuItemMinimizeDfa;
    private javax.swing.JMenuItem menuItemStopSim;
    private javax.swing.JMenu menuSimulation;
    private javax.swing.JMenuItem menuitemAutocomplete;
    private javax.swing.JMenuItem menuitemExit;
    private javax.swing.JMenuItem menuitemExportImage;
    private javax.swing.JMenuItem menuitemInfo;
    private javax.swing.JMenuItem menuitemNewDFA;
    private javax.swing.JMenuItem menuitemOpen;
    private javax.swing.JMenuItem menuitemProperties;
    private javax.swing.JMenuItem menuitemSave;
    private javax.swing.JMenuItem menuitemStartSim;
    private javax.swing.JPanel panelConsole;
    private javax.swing.JPanel panelConsoleTop;
    private javax.swing.JPanel panelContainer;
    private javax.swing.JPanel panelDFADesc;
    private gui.PaintPanel panelDrawArea;
    private javax.swing.JPanel panelHELP;
    private javax.swing.JPanel panelHelpSide;
    private javax.swing.JPanel panelMainDrawArea;
    private javax.swing.JPanel panelTop;
    private javax.swing.JSplitPane splitterInfobar;
    private javax.swing.JSplitPane splitterSimulationBar;
    private javax.swing.JTextPane textDescription;
    private javax.swing.JTextArea textareaInputWord;
    private javax.swing.JTextArea textareaOutput;
    private javax.swing.JToggleButton toggleAddState;
    private javax.swing.JToggleButton toggleAddTransition;
    private javax.swing.JToggleButton togglePointer;
    // End of variables declaration//GEN-END:variables

}
